services:
  - type: web
    name: pulseai-dashboard-frontend
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NEXT_PUBLIC_API_URL
        value: https://pulseai-dashboard.onrender.com
      - key: NEXT_PUBLIC_MOCK_MODE
        value: "false"
      - key: PORT
        value: 10000
    healthCheckPath: /
