services:
  - type: web
    name: pulseai-dashboard-frontend
    env: node
    region: frankfurt
    plan: free
    branch: BENDOH
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: PORT
        value: 3001
    healthCheckPath: /
